### ISSUE TITLE
Handle null language in enricher

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1205]

**Comment by JamieSlome** [comment]
![image](https://user-images.githubusercontent.com/55323451/99254008-997f3700-2809-11eb-988d-f8796d7857d0.png)

@benharvie - photo attached above.

**Comment by benharvie** [comment]
This was a valid response from Octokit as there were no primary languages in the root directory. 

When this is the case, I believe we should check for a null value and v-if display the language box when this is the case (only one case so far). 

Let me know what you think, cheers 👻

**Comment by JamieSlome** [comment]
@benharvie - this sounds good, is there no other way we can infer the language from the contents of the repository?

If no formal or clean way to do this, we can just handle this on the front-end of the platform.

**Comment by benharvie** [comment]
Unfortunately not, Octokit returns null and on the GitHub repository UI it shows no languages, this is why I think in this case it would be best handled in the front end. 

Cheers 👻

**Comment by JamieSlome** [comment]
Okay, I will close this ticket and we can continue to refer to the ticket (550) on the platform repo.

Thanks! 🍰
