### ISSUE TITLE
Check if the repository provided is a valid repo

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1214]

**Comment by JamieSlome** [comment]
@adam-nygate - before accepting the disclosure automatically, can we please add a check to ensure that the repo URL / repo owner and name provided is a valid GitHub repository? This will ensure that we can fork the repository after the merge is successful into staging.

If you are timeboxed, let me know and I will pick this up, thanks! 🍰

**Comment by adam-nygate** [comment]
This is now implemented in #749
