### ISSUE TITLE
Create Pending Payments option in the user profile section

### ISSUE THREAD

**Issue by arjunshibu** [418sec/huntr#1462]
Researchers will be able to see their upcoming payments 👍

**Comment by benharvie** [comment]
Hey @arjunshibu,

Thank you for the suggestion! We have noted this feature and will be looking to implement this in the near future.

Cheers 👻

**Comment by JamieSlome** [comment]
@arjunshibu - thanks for creating the issue. As we are retiring this repository, we will continue to track this request internally.

Cheers! 🍰
