### ISSUE TITLE
Create a GitHub Action for Disclosure Submitted

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1578]
- [x] Re-write validation checks
- [x] Add more thorough checks on PR
- [x] Run Heap Analytics tracking
- [x] Add label to PR

**Comment by JamieSlome** [comment]
Re-formatted, cleaned up the existing validation checks, introduced a new check: `contains-a-valid-repo` and also added:

- [ ] Add label to PR
- [ ] Auto merge
- [ ] Heap tracking

The solution is on #1595 shows a successful run, bar the Heap ID, which has now been defined.

For completion, awaiting switch of on event branch to `staging` and PR from `action/disclosure-submitted` to `staging`.

**Comment by adam-nygate** [comment]
418sec/huntr#1750
