### ISSUE TITLE
As a discloser, I want to be emailed once my disclosure is live as a bounty.

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#1721]
- [x] Draft email copy
- [x] Implement send email logic
- [x] Validate that it works

**Template Link**
https://app.mailjet.com/template/2227033/build

**Info**
Template ID: `2227033`
Template Name: `2227033 - Bounty Live`

**Variables**

- [x] `username`
- [x] `bountyName`
- [x] `bountyURL`

Can assignees please provide information on their individual contributions in the chat log below (e.g Template ID)

**Comment by benharvie** [comment]
Email functionality is nearing completion (branch: `feature/accepted-email-notification`) - if I could just confirm with @zidingz that the email template ID we are using for this notification is `2227033` and also which template variables we plan on importing to this template so I can import them to the workflow as required.

Cheers! 👻

**Comment by JamieSlome** [comment]
This functionality is now moving to `huntr-functions`.

**Comment by benharvie** [comment]
PR opened on `huntr-functions` that fixes this issue: https://github.com/418sec/huntr-functions/pull/296

**Comment by zidingz** [comment]
- [ x] Copy
- [ x] Variables
- [ x] Template Name
- [ x] Template ID

Naisu

**Comment by adam-nygate** [comment]
418sec/huntr#1750
