### ISSUE TITLE
Fix JSON SHA bug

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1738]

**Comment by benharvie** [comment]
https://github.com/418sec/huntr/blob/fb0a9991b56369a109d1ba8526003eaca295f469/tools/disclosure-accepted/get-vulnerability-json.js#L26-L38

I reference `epic/actions-pipeline` branch and retrieve `vulnerabilityJsonSha` from the response of this request. It is my belief that this would be the SHA referencing the file path provided, on the branch provided. However, when eventually updating the vulnerability.json contents the reference updated is on `staging`.

This is not a problem for going on to production but I am unsure as to why this is occurring on `epic/actions-pipeline`.

👻

**Comment by JamieSlome** [comment]
@adam-nygate - when you have a minute, can you look into this, please?

**Comment by adam-nygate** [comment]
The `vulnerabilityJsonSha` is the file contents sha, not the commit sha. Hence when you update the contents of the file, I presume you're not stating a branch, and so it's defaulting to staging and then updating the file corresponding the sha provided (`vulnerabilityJsonSha`), where as, you should be providing a branch to this call, so it knows specifically to update the file on the specific branch you're targetting.

**Comment by adam-nygate** [comment]
418sec/huntr#1750
