### ISSUE TITLE
Test execution of disclosure accepted

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1748]
- [x] Test GitHub Actions workflow
- [x] Test `huntr-functions` webhook

**Comment by adam-nygate** [comment]
418sec/huntr#1750

**Comment by benharvie** [comment]
Email output:

![image](https://user-images.githubusercontent.com/34353676/105513327-13301700-5cca-11eb-8e6a-29396b54f100.png)

**Comment by benharvie** [comment]
Successful Actions test: https://github.com/418sec/huntr/actions/runs/509183868

👻
