### ISSUE TITLE
🪠 Unclog the bounty funnel

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#1750]
### ⁉️ Problem
We've noticed that as the number of disclosures and fixes increases, our time to review/process them significantly decreases.

In December, we believe it took on average, approximately 6 weeks to process a disclosure/fix (contribution).

### 🛠 Solution
We plan on changing the way rewards work so that instead of rewarding when we've reviewed the contribution, we reward more significantly when the maintainer has accepted the fix (and so confirming the validity of both disclosure and fix). We believe that this will reduce the turnaround time to under 2 weeks.

This way huntrs get:
- More money for their valid contributions
- Greater impact knowing that their contribution has been accepted by the open source community
- Quicker turnaround time on their contributions

**Comment by JamieSlome** [comment]
@adam-nygate @psmoros @benharvie @zidingz

To demonstrate the improvements, we can take a look at the life of:

https://github.com/418sec/huntr/pull/1789 - disclosed to fix merge in under 24 hours.

Great job team! 🍰
