### ISSUE TITLE
Release pipeline improvements

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1751]
@benharvie @adam-nygate @zidingz @psmoros

- [x] Merge https://github.com/418sec/huntr-app/pull/619 -> `master`
- [x] Merge https://github.com/418sec/huntr-functions/pull/281 -> `master`
- [x] Resolve conflicts and merge https://github.com/418sec/huntr/pull/1741 -> `staging`
- [x] Merge https://github.com/418sec/huntr/pull/1745
- [x] Merge `huntr` Actions https://github.com/418sec/huntr/pull/1774 -> `staging`
- [x] Resolve https://github.com/418sec/huntr-functions/issues/299
- [x] Resolve https://github.com/418sec/huntr-functions/issues/293
- [x] Publish all MailJet templates
- [x] Publish announcement
- [x] Publish Landen updates https://github.com/418sec/huntr-app/issues/624
- [x] Remove revs.

@benharvie - we can vet further to ensure everything is included. Cheers! 🍰

**Comment by adam-nygate** [comment]
418sec/huntr#1750
