### ISSUE TITLE
🙊 Promote coordinated & collaborative disclosure

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#1798]
### ⁉️ Problem
We've noticed that some maintainers prefer coordinated disclosure over full disclosure. Opinions aside, we believe ensuring that we provide value to the maintainer is what is in the best interest of the community, especially because maintainers will always ultimately decide what is a legitimate vulnerability and what fix makes it into their repository.

### 🛠 Solution
We plan on re-engineering the platform around facilitating interactions between hackers and maintainers for the purpose of finding and fixing vulnerabilities in open source packages.

This means:
- A new disclosure process which enables coordinated disclosure
- A redesigned user experience that focuses on disclosures
- More ways for hackers to earn money by also offering to fix the vulnerability for the maintainer

**Comment by JamieSlome** [comment]
@adam-nygate - what is the status of this ticket?

**Comment by adam-nygate** [comment]
> @adam-nygate - what is the status of this ticket?

It's a long journey! 😝 this used the previous *epic* style ticket, so will leave this open, until we feel concluded on our implementation of coordinated/collaborative disclosure.
