### ISSUE TITLE
As a user, I want to contact huntr using a contact form.

### ISSUE THREAD

**Issue by zidingz** [418sec/huntr#1820]
- [ ] Create a name field
- [ ] Create an email field
- [ ] Create a phone field (optional)
- [ ] Create a custom message field
- [ ] Create a submit button
- [ ] Create a title for page
- [ ] Create a subtitle for page
- [ ] Create metadata for page (metatags)
- [ ] Create reason field/dropdown
- [ ] Write copy for page + display on page
- [ ] Implement with Tailwind CSS
- [x] Create a dedicated contact us page with Nuxt
- [x] Create link from main page burger to contact page

On completion:

- [ ] Create validation for each field
- [ ] Create form submission validation
- [ ] Display errors on invalid fields
- [ ] Display the contents of the form in JSON in console
- [ ] Send to 418sec team

**Comment by adam-nygate** [comment]
Closing this as it's now located on the new repo
