### ISSUE TITLE
New CSP Policy For Huntr Disallow External Images From Loading.

### ISSUE THREAD

**Issue by DEMON1A** [418sec/huntr#1880]
- I Just Noticed That Huntr Don't Load External Images Anymore Due To CSP Policy. But It's Used On The Markdown And Should Be Allowed. I Would Recommend Allowing Image Uploads Only For Specefic Sources That Will Be Whitelisted On The CSP Policy. Or Huntr Can Create It's Own Service For Hosting External Images.

**Comment by JamieSlome** [comment]
@DEMON1A - thanks for raising this issue - could you please attach a bounty URL that demonstrates this.

I will keep you posted with any updates.

Cheers! 🍰

**Comment by DEMON1A** [comment]
Hey, Here's The Bounty URL: https://www.huntr.dev/bounties/2-pip-papermerge/, See The Console Output

**Comment by JamieSlome** [comment]
@DEMON1A - as we are looking to retire this repository, we have now moved this issue to our internal tracking system.

Thanks for reporting! 🍰

**Comment by JamieSlome** [comment]
@DEMON1A - implemented and fixed! 👍
