### ISSUE TITLE
Forks Doesn't Get Updated That Leaves The Fixers With Old Versions To Edit.

### ISSUE THREAD

**Issue by DEMON1A** [418sec/huntr#1881]
- I Was About To Create a Fix For https://github.com/418sec/docs After Getting Where's The Injection Point. But I Got That The Repo Is Out-Dated From Long-Time Ago And I The Vulnerable Code Doesn't Exists Yet, Do You Think Forks Should Be Updated And Merged With The New Version Of The Original Projects Every Day Maybe. Or When Someone Is Forking It. That Will Help a Lot With The Fixing Processes.

**Comment by JamieSlome** [comment]
Hello @DEMON1A 👋  - thanks for raising this with us!

We are definitely looking to automate this in the near future, as we see that this will allow our users to submit fixes without issue.

I will manually update this repository for now, and keep this issue open.

Cheers! 🍰

**Comment by JamieSlome** [comment]
@DEMON1A - re-based this repo - thanks! 🍰

**Comment by JamieSlome** [comment]
Leaving this for later usage:

https://github.com/wei/pull

https://stackoverflow.com/questions/23793062/can-forks-be-synced-automatically-in-github/38171158

**Comment by JamieSlome** [comment]
Hey @DEMON1A - also closing this issue as we have added this as a task internally to be tracked and implemented.

Cheers! 🍰
