### ISSUE TITLE
Huntr email is sending broken URLs for pip packages.

### ISSUE THREAD

**Issue by DEMON1A** [418sec/huntr#1964]
- When you submit an issue related to pip package and the bounty is live. huntr does send you an email about that the bounty is live. the URL it's sending doesn't match with the latest huntr updates. instead of using `pypi` it's still using `pip` on the URL.

**Comment by JamieSlome** [comment]
Hello @DEMON1A 👋 - thanks for reporting this bug.

I have just implemented a fix for this, and we shouldn't see this problem again.

Thanks! 🍰

**Comment by JamieSlome** [comment]
https://github.com/418sec/huntr-functions/pull/363
