### ISSUE TITLE
`Copy git clone cmd` results in `git clone false` if not forked

### ISSUE THREAD

**Issue by doshmajhan** [418sec/huntr#1980]
When clicking the `Copy git clone cmd` the resulting copied text is `git clone false` if you have not previously forked the project. It may be helpful to display some sort of notice to the user letting them know they have to fork it first, or either disable the option to copy the git command until the user has forked the project.

**Comment by JamieSlome** [comment]
Hello 👋 @doshmajhan - thanks for raising this issue.

We have tracked this internally, and will update this ticket when we have remediated the bug.

Cheers! 🍰

**Comment by JamieSlome** [comment]
@doshmajhan - fixed! 🎉 

Feel free to have a play around, and let me know if you have any more questions, cheers! 🍰
