### ISSUE TITLE
Silent error when saving PayPal withdrawal address

### ISSUE THREAD

**Issue by doshmajhan** [418sec/huntr#1981]
When adding PayPal withdrawal address to your profile, if you supply an invalid address it will fail silently, only when you supply a valid address do you get a notification: `Save succeed!`  The graphql call made in the background is returning a `200 OK` with the error in the response: 
```
{"data":null,"errors":[{"path":null,"locations":[{"line":1,"column":25,"sourceName":null}],"message":"Variable 'paypal_address' has an invalid value. Unable to parse `doshmajhan` as a valid email address."}]}
```
The `Unable to parse doshmajhan as a valid email address.` portion of the error should be surfaced to the user.

**Comment by JamieSlome** [comment]
@doshmajhan - keep 'em coming!

We are working on a patch now, cheers! 🍰

**Comment by JamieSlome** [comment]
@doshmajhan - thanks for reporting, this has now been resolved.

We now show an error to the user on the failure of the GraphQL call.
