### ISSUE TITLE
Create a personal statistics, graphs and metrics section displaying a users success on the platform.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1984]
Display personalized metrics and statistics to users. This will help them better understand their quality of contributions, as well as the quantity of them.

**Comment by adam-nygate** [comment]
Hey @JamieSlome, can you check out #1982 before working on this?

**Comment by JamieSlome** [comment]
Hello @adam-nygate - I hope you had a great weekend.

Already finished! 👍

**Comment by adam-nygate** [comment]
> Hello @adam-nygate - I hope you had a great weekend.
> 
> Already finished! 👍

Just for future reference 👍 😄

**Comment by JamieSlome** [comment]
Great! 👍
