### ISSUE TITLE
Send weekly personalized e-mails with all of your most recent disclosures and interactions.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1986]
- [ ] Send weekly e-mail with recent disclosures
- [ ] Send weekly e-mail with all other interactions including messages

**Comment by adam-nygate** [comment]
Hi @JamieSlome, can you please groom this ticket. If we don't have a definition yet, feel free to leave it as a note until grooming.

**Comment by psmoros** [comment]
Deemed no longer promising by @JamieSlome
