### ISSUE TITLE
Create a discussion forum where disclosers and maintainers can discuss their reports.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#1988]
- [ ] Create a global chat room
- [ ] Create language based chat rooms
- [ ] Create CWE based chat rooms

**Comment by adam-nygate** [comment]
Hi @JamieSlome, can you please groom this ticket. If we don't have a definition yet, feel free to leave it as a note until grooming.

**Comment by psmoros** [comment]
Closed as N/A by @JamieSlome  :) Hope discord serves this purpose it in the meantime!
