### ISSUE TITLE
Send maintainers an email, if we're unable to reach them via a GitHub Issue

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#1994]
- [x] Identify an automatable way to grab a maintainers email
- [x] If GitHub issues are disabled, email the maintainer instead
- [x] Copy for email. Template ID `2890413 - Issues Disabled Maintainer Email`

**Comment by benharvie** [comment]
Found a useful endpoint that publishes a user's email via. their published commits: https://api.github.com/users/jamieslome/events/public

**Comment by adam-nygate** [comment]
> Found a useful endpoint that publishes a user's email via. their published commits: https://api.github.com/users/jamieslome/events/public

Some may also have it here: https://api.github.com/users/jamieslome

We also need to preventing grabbing GitHub emails (where they don't proxy emails on to users)

**Comment by JamieSlome** [comment]
@benharvie - great work! 🎉 

This has now been deployed, and e-mails will be sent to publicly visible e-mails when GitHub Issue creation fails.

Thanks.
