### ISSUE TITLE
Old advisory ID's do not work

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2001]
Create a way to get old advisory ID (`1-pip-networkx`) pages to render correctly

**Comment by JamieSlome** [comment]
https://huntr.dev/bounties/1-pypi-networkx/

**Comment by JamieSlome** [comment]
This is not a valid URL since the ID has changed to include `pypi`.

We can close this issue, unless we want to address the issue of supporting outdated URLs.

**Comment by adam-nygate** [comment]
@JamieSlome I've updated the ticket to reflect the need to have something that actively corrects for old IDs

**Comment by JamieSlome** [comment]
Implemented and deploying now, thanks! 🎉
