### ISSUE TITLE
Ensure maintainer and discloser notifications go into the main inbox folder.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2002]
Depending on filters in a user's e-mail inbox, the e-mail can sometimes enter the promotions folder.

We want to ensure that disclosure notifications are dropped into the main inbox folder for both the reporter and maintainer.

**Comment by adam-nygate** [comment]
https://documentation.mailjet.com/hc/en-us/articles/360042625454-Why-are-my-marketing-emails-landing-in-Gmail-s-Promotions-Tab-

**Comment by JamieSlome** [comment]
@zidingz @adam-nygate - all templates deployed and desired mailbox checks made too! 🎉 

Feel free to close when ready @adam-nygate ❤️
