### ISSUE TITLE
Contact and give access to advisories for administrative and recently contributing maintainers.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2006]
Based on https://github.com/nodejs/node/issues/38748

Thanks, @MylesBorins for the feedback!

**Comment by aduh95** [comment]
If I may suggest, I think you should avoid pinging anyone at all: by default maintainers of GitHub repo receive a notification every time an issue is opened on one of their repo – unless they've opted out, and it's probably because they don't want a notification anyway. So the tagging is at best not necessary, it may be relevant to ping recent contributors only if the issue receives no response after some time.

**Comment by JamieSlome** [comment]
@aduh95 - thanks for the feedback.

We are in the process of re-building our notification service on new disclosures, and will definitely address this when we re-implement.

Let me know if you have any more feedback, but certainly will have this covered in our upcoming releases.

**Comment by MylesBorins** [comment]
If I could make a suggestion. Don't open any issue on GitHub, and especially don't do so using bots.

Reporting of vulnerabilities should never happen via public disclosure

**Comment by adam-nygate** [comment]
> If I could make a suggestion. Don't open any issue on GitHub, and especially don't do so using bots.
> 
> Reporting of vulnerabilities should never happen via public disclosure

Noted. For clarity, our intention moving-forward is to try to contact the maintainer via any means off-GitHub (e.g. email/contact mechanism on SECURITY.md), and only using GitHub as a last resort.

Hoping to get this live soon!

**Comment by MylesBorins** [comment]
@adam-nygate while I am glad to hear that you are saying your are rolling out a change and iterating I see 15 Issues opened just in the last 24 hours

https://github.com/issues?page=1&q=is%3Aissue+is%3Aopen+author%3Ahuntr-helper

What your team is doing is not secure and is making the overall OSS ecosystem less secure in my opinion. You are ignoring what folks have identified in their `SECURITY.md` file, you are partially disclosing vulnerabilities, and forcing maintainers to sign up for your private service to get more details.

Would your team be willing to stop opening public issues that disclose details about vulnerabilities today?

**Comment by adam-nygate** [comment]
> @adam-nygate while I am glad to hear that you are saying your are rolling out a change and iterating I see 15 Issues opened just in the last 24 hours
> 
> https://github.com/issues?page=1&q=is%3Aissue+is%3Aopen+author%3Ahuntr-helper
> 
> What your team is doing is not secure and is making the overall OSS ecosystem less secure in my opinion. You are ignoring what folks have identified in their `SECURITY.md` file, you are partially disclosing vulnerabilities, and forcing maintainers to sign up for your private service to get more details.
> 
> Would your team be willing to stop opening public issues that disclose details about vulnerabilities today?

Sorry for not being clearer - we are deploying a change ASAP (🤞 today) that will do what you've just described 😊

As in, if a policy is identified, prevent any automations and enable us to manually facilitate.

**Comment by JamieSlome** [comment]
@MylesBorins - this has now been deployed! 🍰 😃
