### ISSUE TITLE
Webhooks and RSS feeds to notify maintainers and hackers 

### ISSUE THREAD

**Issue by 0xcrypto** [418sec/huntr#2007]
I am a discord junkie and most of the time, I put discord webhooks everywhere to get notified about the service. If huntr.dev would have allowed webhook configuration, it would be awesome to get a notification of any validation of disclosure on a webhook. This could also be helpful for maintainers to get a notification in their respective service like discord, slack etc where they are more active than the issue tab of github.

Also, some companies parse RSS feeds to get notified about latest research work. So if there was some RSS, it would have been really helpful to get a daily or weekly bundle of advisories on huntr.dev.

**Comment by adam-nygate** [comment]
Hey @0xcrypto, thanks for the request!

Our platform is actually completely powered by a GraphQL API. We're iterating quickly and so the API is likely to change often, but feel free to create something that polls the appropriate endpoint to get the data you want :)

Let me know if you need any help.

**Comment by psmoros** [comment]
closing as something we won't do :)
