### ISSUE TITLE
Facilitate `directus` disclosures

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2008]
- [x] Email them with markdown files containing the disclosure information
- [x] https://huntr.dev/bounties/1-other-directus/directus/
- [x] https://huntr.dev/bounties/2-other-directus/directus/
- [x] https://huntr.dev/bounties/3-other-directus/directus/

**Comment by JamieSlome** [comment]
All 3 reports have been sent over to the directus team.

Cheers! 🍰
