### ISSUE TITLE
Review retroactively assigned CVEs

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2010]
- [ ] Decide if retroactive-duplicate CVEs should be displayed on advisories
- [ ] Decide if users with duplicate advisories should be disconnected
- [ ] Update the data

**Comment by psmoros** [comment]
@adam-nygate  can we track this internally and close it or do you consider it to be a user facing benefit?

**Comment by adam-nygate** [comment]
This was completed.
