### ISSUE TITLE
Remove the title of undisclosed reports in https://huntr.dev/bounties/*-other-*

### ISSUE THREAD

**Issue by zer0h-bb** [418sec/huntr#2023]
Remove the title of the reports that are undisclosed.

![image](https://user-images.githubusercontent.com/77683857/120120335-deaef900-c19c-11eb-879c-f7933119f607.png)

A rogue party having the name of the vulnerability as well as the associated repository could find the vulnerability before the maintainer can fix it.

I know that you are aware of this issue and have already taken several steps in this regard :)

Best regards,
zer0h

**Comment by JamieSlome** [comment]
Note to self: consider including converting new vulnerability IDs to GUIDs.

**Comment by adam-nygate** [comment]
This has now been fixed.
