### ISSUE TITLE
Upvote / downvote reports

### ISSUE THREAD

**Issue by zer0h-bb** [418sec/huntr#2024]
Hi, it could be great to let the users upvote or downvote disclosed reports and add a tab where we can filter reports based on their reputation (just like what hackerone does)
It can be an incentive for hunters to report higher quality bugs :)

**Comment by JamieSlome** [comment]
@zer0h-bb - thanks for the suggestion! 👏 

We have discussed internal reputation scoring and judging mechanisms, but have not committed just yet.

We will keep you updated on this ticket of any changes on this!

**Comment by psmoros** [comment]
@JamieSlome your thumbs up is a support for this initiative rather than an ACK to @zer0h-bb right? 

_btw we miss you @zer0h-bb hope your studies are going well!_

**Comment by JamieSlome** [comment]
@psmoros - yep!

**Comment by zer0h-bb** [comment]
Thank you so much @psmoros ❤

**Comment by JamieSlome** [comment]
@psmoros - ready to close? This is live and kickin' 🛴 ❤️ 🥇 🥜
