### ISSUE TITLE
Tune target-finder

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2027]
- [x] Reduce inconsequential vulnerability reports
- [x] Encourage reports against high-impact projects
- [x] Reduce project farming

**Comment by TheCrott** [comment]
How do you encourage hackers to report against high-impact projects? By giving more points to popular and high-impact projects?

**Comment by adam-nygate** [comment]
> How do you encourage hackers to report against high-impact projects? By giving more points to popular and high-impact projects?

Exactly :)

**Comment by JamieSlome** [comment]
@adam-nygate - closing! 🎉
