### ISSUE TITLE
As a maintainer, I want to be able to choose when an advisory is fully disclosed.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2028]
@zer0h-bb - thanks for the suggestion.

**Comment by adam-nygate** [comment]
We'll look to enable the maintainer to decide the visibility of the advisory post-validation - will update the title to reflect this.

**Comment by JamieSlome** [comment]
@adam-nygate - just a technical update - we now have the capability to update visibility via a `visible` data prop on each vulnerability report.

**Comment by psmoros** [comment]
closing as duplicate of #2143 :)
