### ISSUE TITLE
Cannot select branch if repo has > 30 branches

### ISSUE THREAD

**Issue by davwheat** [418sec/huntr#2033]
The GitHub API only returns the first 30 branches, with later branches needing a `?page=X` query param.

The website doesn't watch for this, meaning that if the repo has over 30 branches, only the first 30 will appear, making you have to delete branches to submit the patch.

**Comment by JamieSlome** [comment]
Thanks for the suggestion @davwheat - I have gone ahead and added this to our public roadmap board.

I will keep you updated with the progress of this ticket.

**Comment by JamieSlome** [comment]
For now, I have implemented a dropdown populated with 100 results included. If the use case appears, I will re-implement with pagination for a greater number of branches.
