### ISSUE TITLE
As a maintainer, I want all report information to be private until fully disclosed.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2036]
Thanks for the suggestion @davwheat.

- [x] New UI for private report page (@psmoros)
- [x] Report meta
- [x] Conversation
- [x] Permalinks

**Comment by adam-nygate** [comment]
Looking to expand the scope of this, so will adjust the title

**Comment by JamieSlome** [comment]
Cool!

**Comment by adam-nygate** [comment]
@JamieSlome perhaps we should look to re-implement the way we privatise the vulnerability object as a "kill two birds with one stone" approach?

**Comment by JamieSlome** [comment]
For sure, this makes more sense.

**Comment by adam-nygate** [comment]
@JamieSlome shall we merge #2023 into this as well?

**Comment by JamieSlome** [comment]
Yes, #2023 - I am sure we will cover auth'ing the entire contents of the page, so this will naturally fall under the scope.

**Comment by 0xcrypto** [comment]
Private reports have vulnerable code's reference publicly accessible which should be private. I see submitted patch message no longer has link to the fix. Is this intended?

**Comment by davwheat** [comment]
Both the patch and merge messages still have links for me.

**Comment by 0xcrypto** [comment]
Yeah just refreshed the page and they came back.

**Comment by JamieSlome** [comment]
@psmoros is currently working on UI for this as we speak!

**Comment by psmoros** [comment]
finished! 🚀
