### ISSUE TITLE
Fix the ordering of listings on the hacktivity page.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2038]
Reported by @zer0h-bb.

<img width="1193" alt="Screenshot 2021-06-15 at 10 51 07" src="https://user-images.githubusercontent.com/55323451/122032536-a415a500-cdc7-11eb-94a8-17be335e7d16.png">

It looks like advisory does not populate at the top of the hacktivity as expected, based on the date it was validated.

**Comment by psmoros** [comment]
@JamieSlome what's wrong here?

**Comment by JamieSlome** [comment]
@psmoros - believe this issue has since been fixed.
