### ISSUE TITLE
Create a search utility to find all advisories against a repository.

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2039]
It can be difficult for both researchers and maintainers to find disclosures, intuitively. 

- [ ] Input a repository URL or owner/name
- [ ] Display a listing of all repository advisories
- [ ] Show as private or public on returned listings

**Comment by JamieSlome** [comment]
@adam-nygate - thoughts?

**Comment by adam-nygate** [comment]
I think "As a maintainer, I want to be able to see all advisories against my organisation/repository" (#2068) will make sense soon, but the above is much wider than that.

What's the _why_?

**Comment by Cyberlytical** [comment]
I was about to create an issue about this, "As a researcher, I want to be able to search for a repo within the Hactivity page to see the disclosed reports for said repo"
Helps prevent any duplicate reports, or testing in a functionality which has already been tested extensively.

**Comment by adam-nygate** [comment]
Thanks for that @Cyberlytical.

Just to make sure I understand, you'd like for some functionality that helps with:
- Preventing duplicate reports
- Informing you of whether the target repository has been extensively tested

A side question: Would you say that you're more interested in finding vulnerabilities against repositories that have been highly reported against by others, or a repository that has few/no reports?

**Comment by Cyberlytical** [comment]
Hey @adam-nygate 

> Preventing duplicate reports

Yeah, it would be under the scenario where a fix is taking a while, not common as far as I know. But it would be handy.
> Informing you of whether the target repository has been extensively tested

Main thing I'd be looking for is something that shows what's already been tested, the ability to see reports so I know where not to waste my time (I.e- Login form has already received multiple reports covering XSS and SQLi, therefore - No need to test for those bugs in that functionality.

> A side question

Interesting question, I'd normally be more inclined to test on one with few/no reports - It would depend on the size of the repo, how much their is to test...and generally how confident I'm feeling. 

My use case would be, looking through the disclosed reports for the repo, and comparing it against the repo - Seeing where I could test that others haven't found vulnerabilities in.


Thanks!

**Comment by adam-nygate** [comment]
Ah, thanks for the explanation, I'll look to create the following user story which should address this:
- [ ] #2050

**Comment by am0o0** [comment]
Hi guys 
This is very critical for me as a bug bounty hunter that know whether a repo is tested yet or not
Plz make this task as your highest priority.

**Comment by slackero** [comment]
> [As a researcher, I want to know what repositories have already been tested, so that I do not waste my time. #2050](https://github.com/418sec/huntr/issues/2050)

For me this is the most important, find all reports related to the repos for which I am the maintainer. All I can see at the moment is the number of reports in the small flag, nothing else.

**Comment by JamieSlome** [comment]
@slackero - we are working on this feature as we speak. But to be more specific, for anyone else subscribed to this issue, we are building out a similar functionality for maintainers.

Take a look at:

https://github.com/418sec/huntr/issues/2068

**Comment by adam-nygate** [comment]
Hi all,

We've now shipped the following:
- #2068
- #2050 

We decided against a search functionality for now as we believe the above tickets addressed the needs as described in the above conversation.

In the future, we look to ship #2120 which will address the duplicate reports issues.
