### ISSUE TITLE
On "Confirm Fix", the activity log can show the incorrect recipient of the fix bounty until refreshed.

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2040]
> As a maintainer I click "Confirm Fix" then select the branch and commit that fixes the vuln. I also select the person who receives the bounty (in this case davwheat). When the modal is completed and closed the page mentions that I am receiving the bounty for fixing, only upon refreshing is the right user shown.
-- @luceos

**Comment by JamieSlome** [comment]
@psmoros - can we prioritize this today?

**Comment by JamieSlome** [comment]
Solved this with a client-side refresh once the fix has been confirmed.
