### ISSUE TITLE
On the wallet page, new users see a blank page

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2044]
Reported by @timz99.

**Comment by JamieSlome** [comment]
@psmoros - can we prioritize this today? We just need to validate this is not an issue.

If not, feel free to close the ticket and mark as invalid.

**Comment by JamieSlome** [comment]
Solved! When a user signs up and did not have any settings set, we were checking if they had a PayPal address to display a warning.

Deploying the fix now 🎉
