### ISSUE TITLE
Suggestions to generate some revenue 

### ISSUE THREAD

**Issue by 0xcrypto** [418sec/huntr#2048]
Huntr.dev is doing amazing work by providing monetary rewards to hackers. But I am unsure how far huntr can go depending on just investor's money. So here are some suggestions to generate some revenue to support the Huntr.dev team as well as hackers:

## Accept donations
There are many people willing to support the cause and provide monetary support. 

## Allow maintainer to pay the bounties
There are maintainers running bug bounty programs on their own or considering to start a bug bounty program. Huntr.dev can provide them a platform and help them get started in no time.

## Web Monetization
Web Monetization (https://webmonetization.org/) is a new way to monetize the content. Just put an interledger address in monetization meta tag on each report, a small amount of subscription will be paid to the interledger address from coil subscription of readers.

**Comment by JamieSlome** [comment]
@0xcrypto - thanks for the thorough detail and ideas here! 👏 

For transparency, we have considered various ideas including the ones mentioned. One that we are experimenting with more closely is allowing maintainers to sponsor/donate into the existing implementation of prize pots. We have seen maintainers motivated to reward researchers out of their own pocket, and see this as a potential avenue! But specifically, our intention is to crack an amazing user experience for researchers and maintainers, firstly!

Will keep you posted! 🎉

**Comment by psmoros** [comment]
Thanks for the suggestion @0xcrypto! Will close as well-received :)
