### ISSUE TITLE
When Editing a Markdown Report the Report Does not get Rerendered after and shows the Markdown Source instead

### ISSUE THREAD

**Issue by meme-lord** [418sec/huntr#2052]
I noticed when editing a report the markdown wouldn't be rendered after saving and instead would show it with the backticks and everything until I refreshed the page.

**Comment by JamieSlome** [comment]
@psmoros - can we look to take this on?

**Comment by psmoros** [comment]
> @psmoros - can we look to take this on?

I'll look into it after lunch :)

**Comment by psmoros** [comment]
Hey @meme-lord I can't replicate the issue... what browser are you using? A video / gif of the bug would be very helpful! Thanks 🦜

**Comment by meme-lord** [comment]
Seems to work now, maybe it was noscript. Apologies
