### ISSUE TITLE
As a maintainer, I want to see a list of all reports against my repositories.

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2068]
- [x] Establish a relationship from a maintainer to a repository - 418sec/huntr-platform#1229
- [x] Create a query that lists repositories & reports for a given maintainer - 418sec/huntr-platform#1230

**Comment by JamieSlome** [comment]
Overlaps with #2039?

**Comment by adam-nygate** [comment]
> Overlaps with #2039?

#2039 is being broken down into many tickets (this one and #2050)

**Comment by luceos** [comment]
Oh yes please. Right now when logging in there's no index of reports anywhere, no list of repositories I am linked to, nothing. The only way to use huntr.dev as a maintainer right now is to use the email sent.

**Comment by slackero** [comment]
Yes, this is urgent. I was too fast deleting the report emails and the pages also were not in my browser's history (why ever).

If such list of all/filtered by type reports is not recommend by whatever reason, maybe send a reminder after some days.
