### ISSUE TITLE
As a user, I want to be able to pass any valid GitHub repository URL into `target-finder`.

### ISSUE THREAD

**Issue by geeknik** [418sec/huntr#2071]
This is more of an annoyance than anything functional. For example, at the top of `https://huntr.dev/bounties/1625486747136-riyadhalnur/node-base64-image/`, it says Code Injection in [riyadhalnur/node-base64-image](https://www.github.com/riyadhalnur/node-base64-image).  It links to `www.github.com`, which in and of itself isn't really an issue, however, if you right click and copy that link and then drop the link into the box at `https://huntr.dev/bounties/disclose/`, the page throws an exception and says `Please enter a valid GitHub repository URL, including https://...`

![2021-07-05_10-38](https://user-images.githubusercontent.com/466878/124495053-24b43980-dda7-11eb-96f7-213336acc2cf.png)

**Comment by adam-nygate** [comment]
@psmoros I think we have to re-write how we check the repo URL - will work with you on it

**Comment by ranjit-git** [comment]
If you remove www from github repo url then it will be accepted

**Comment by michaellrowley** [comment]
Assuming that huntr uses Regex, this would match the above URL and a few other edge cases:
```regex
^(https:\/\/)?(www\.)?github.com\/[a-zA-Z0-9\-\_]{1,}\/[a-zA-Z0-9\-\_]{1,}(\/)?$
```

**Comment by JamieSlome** [comment]
Sorted and now live 🎉
