### ISSUE TITLE
🔢 Suggestion

### ISSUE THREAD

**Issue by B3EF** [418sec/huntr#2076]
### 👍🏻 reward suggestion
* if you can , then keep same bounty for different family of bugs and reduce 50% for same kind family of multiple reports.
because the maintainer will be already knowing that his/her repo is vulnerable to this family of bug then it will be their job to fix at other possible end points, if there is same bounty for different family of bugs then the reporter will show some dedication in his/her work as they will try to find different kind of bugs other than reporting the same one at the same repos different path.
* it would be also nice if a sheriff is assigned to check the cvss score , as while going through some bugs reported recently , it feels like point farming is going on with huntr , and it will also encourage the maintainers to use huntr , other than considering as a spam(some maintainers consider this as a spam from my recent experience )
* at last , it would be nice if bounty provided to well known projects are the same, ie consider Projects like October CMS... these projects holds multiple dependent repos, here in these cases only the main one will be famous and have more stars forks and clones, there is chances for the bug to be found has to be in its dependent repo , so it would be nice if all the dependent repos under same maintainer which combines in to a single project will hold same bounty as reward.

![](https://cdn.dribbble.com/users/12570/screenshots/1616035/anim-reward-granted.gif)

**Comment by B3EF** [comment]
These are just suggestions from my point of view .

**Comment by b1nslashsh** [comment]
Agreed 💯
