### ISSUE TITLE
Sanitization in Comment section seems to be performing wrong operation

### ISSUE THREAD

**Issue by B3EF** [418sec/huntr#2081]
while pasting or adding code in the code pamphlet of markdown in the comment section , the input sanitize function present there  is removing the code from the pamphlet ;
i was trying to comment this 
``` <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:relative" width="300" height="200" overflow="hidden">
<image x="10" y="10" width="276" height="110" xlink:href="http://0a0fdf524388.ngrok.io"/>
<path d="M0 150h300v10H0z"/>
</svg> 
```
and after submitting i have got this
![](https://cdn.discordapp.com/attachments/749019614352244777/864947367860764722/Capture.PNG)

**Comment by adam-nygate** [comment]
Hey @B3EF,

I'm not sure if I see the issue. When testing your message, it renders like this:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/4394852/125758623-f1f0a4f6-d54f-4fe0-85ab-9926a7215815.png">

Could you highlight what's missing?

**Comment by B3EF** [comment]
sorry i have pasted the wrong content
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:relative" width="300" height="200" overflow="hidden">
<image x="10" y="10" width="276" height="110" xlink:href="https://en7uzqeqppd0apu.m.pipedream.net"/>
<path d="M0 150h300v10H0z"/>
</svg>
```

**Comment by B3EF** [comment]
this was the content I was trying to include

**Comment by adam-nygate** [comment]
This is what I get:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/4394852/125777823-6a79ba19-83e9-459e-8d79-73b0e30677cc.png">

**Comment by B3EF** [comment]
![Screenshot from 2021-07-15 17-06-30](https://user-images.githubusercontent.com/43377443/125781845-0e9985eb-60e5-48bb-8870-5972494df962.png)
but i am getting this did you have tried pasting it inside ```

**Comment by B3EF** [comment]
let me check whether its my browsers issue too

**Comment by B3EF** [comment]
![Screenshot from 2021-07-15 17-12-14](https://user-images.githubusercontent.com/43377443/125782514-0ff7a424-9f0f-4b55-96ec-e555b645f9ee.png)
tried with a different browser too.

**Comment by adam-nygate** [comment]
It's because the markdown is incorrectly formatted, you must use a newline after each ` ``` `, e.g:
```
\```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="position:relative" width="300" height="200" overflow="hidden">
<image x="10" y="10" width="276" height="110" xlink:href="https://en7uzqeqppd0apu.m.pipedream.net"/>
<path d="M0 150h300v10H0z"/>
</svg>
\```
```

(without the preceding \\'s)

**Comment by B3EF** [comment]
oh ok thanks for the help

**Comment by adam-nygate** [comment]
No worries :)
