### ISSUE TITLE
account takeover Vulnerabilities 

### ISSUE THREAD

**Issue by am0o0** [418sec/huntr#2082]
Hi dears
I can't find the " Improper Authorization" with CWE-285 in disclosure Titles
Also there is nothing in titles about account takeover vulnerabilities.
Thanks so much hunt team.

**Comment by JamieSlome** [comment]
@adam-nygate - can add CWE-285?

https://cwe.mitre.org/data/definitions/285.html

**Comment by JamieSlome** [comment]
@amammad - added to the CWE list - cheers! 🎉
