### ISSUE TITLE
send notifications when in vulnerability disclosure page, repository's maintainers send any feedback on our disclosures

### ISSUE THREAD

**Issue by am0o0** [418sec/huntr#2083]

**Comment by am0o0** [comment]
I like to get notifications with my email to answer quickly the maintainers and also be aware of my disclosure's results

**Comment by JamieSlome** [comment]
@amammad - just so I understand, do you mean that when a maintainer comments on an advisory, or they mark it as valid or invalid you want to receive e-mail updates?

We do currently support this! I have taken a look at our e-mailing service and your specific disclosure, and we have been sending e-mails to the e-mail associated with your GitHub account.

Let me know! 🎉

**Comment by amammad** [comment]
yah this is my point 
https://huntr.dev/bounties/890b378c-7b9a-473e-9ab5-32daec882b16/
when the maintenaner send some feedback to this report i dont get any email

**Comment by 0xcrypto** [comment]
@amammad it goes to promotion tab in gmail. Also check spam folder, just in case.

**Comment by am0o0** [comment]
yes i see them tnk you so much dear
