### ISSUE TITLE
how I can choose proper title for "account take over" in my reports?

### ISSUE THREAD

**Issue by am0o0** [418sec/huntr#2084]
is it any cwe for it or somethings else ?

**Comment by am0o0** [comment]
I find a CSRF vulnerability that lead to Account take over and I think it is very better to set title to "Account take over" rather than "CSRF"

**Comment by 0xcrypto** [comment]
> I find a CSRF vulnerability that lead to Account take over and I think it is very better to set title to "Account take over" rather than "CSRF"

There is a difference between vulnerability, attack and security impact. Account takeover is the resulting impact of an attack that takes advantage of a vulnerability. CWE is common weakness enumeration that tries to explain a vulnerability that can have a security impact.

**Comment by am0o0** [comment]
aha thanks so much dear 0xcrypto,
I just want to know for account take over impact how I name a report title ? I mean what kind of CWE I should set on my report title ?

**Comment by 0xcrypto** [comment]
> aha thanks so much dear 0xcrypto,
> I just want to know for account take over impact how I name a report title ? I mean what kind of CWE I should set on my report title ?

As you mentioned it is an account takeover via CSRF, you should mention the "account takeover" in the report as impact and select CWE-352 which explains CSRF.

**Comment by am0o0** [comment]
OK
thank you so much dear 0xcrypto.
