### ISSUE TITLE
The disclosure must happen after the researcher validate the fix also

### ISSUE THREAD

**Issue by am0o0** [418sec/huntr#2086]

**Comment by 0xcrypto** [comment]
+1 to this. Sometimes, hackers have their secret tricks they do not want others to know about.

**Comment by am0o0** [comment]
+1 to this. 
The recon part of Open source bug bounty is the big part of a bug bounty hunter.
as the CWE's title, repo name, the disclosure is accessible for anyone, then the bug bounty hunter efforts in recon will be wasted.
so the Disclosure and its full title in my opinion should depend on the bug bounty hunter choice.

**Comment by JamieSlome** [comment]
@amammad @0xcrypto - this is no longer possible, as we have made improvements to our authorization capabilities.

We can close this issue. Please let me know if there are still outstanding issues and we can re-open.
