### ISSUE TITLE
If a vulnerability hasn't been fixed yet, The CWE Title with repository name must be hidden

### ISSUE THREAD

**Issue by am0o0** [418sec/huntr#2087]
Because if anyone knows that there is a vulnerability in this repository, it can find it **faster** and with **more assurance**

**Comment by TheCrott** [comment]
Redacted title like in hackerone 's hacktivity?

**Comment by am0o0** [comment]
yes like that

**Comment by am0o0** [comment]
Also many Repository's maintainers want to report security issues to them totally privately and maybe with our disclosures that the CWE Title and REPO's name are completely clear, they get worry about this.

**Comment by JamieSlome** [comment]
@amammad - this has now been delivered! 🎉
