### ISSUE TITLE
CORS issues in the Mozilla version of the huntr extension due to bad manifest.json permissions

### ISSUE THREAD

**Issue by zer0h-bb** [418sec/huntr#2088]
The Mozilla version of the extension doesn't work because the extension isn't allowed to send requests to <https://mnk2smepzzdp5djxpbthzr6odq.appsync-api.eu-west-1.amazonaws.com/>.
By modifying the `manifest.json`, it should work : 
```
{
  "manifest_version": 2,
  "name": "huntr.dev GitHub Extension",
  "version": "0.1.0",
  "description": "View huntr.dev bounty rewards on GitHub as you browse code repositories.",
  "content_scripts": [
    {
      "js": [
        "js/background.js"
      ],
      "matches": [
        "https://github.com/*/*"
      ]
    }
  ],
  "permissions": [
    "webRequest",
    "https://mnk2smepzzdp5djxpbthzr6odq.appsync-api.eu-west-1.amazonaws.com/*"
  ],
  "web_accessible_resources": [
    "html/bounty_tab.html"
  ],
  "icons": {
    "16": "img/logo_16.png",
    "24": "img/logo_24.png",
    "32": "img/logo_32.png",
    "48": "img/logo_48.png",
    "128": "img/logo_128.png"
  }
}
```
There is another minor issue when the extension want to build `bounty_tab.html`, it loads a svg file from huntr.dev (`https://huntr.dev/_nuxt/img/mouse-warrior.06d7a93.svg`), and this is prevented by the CSP rules of github.com

Thank you geeknik for the solution :)

**Comment by geeknik** [comment]
> There is another minor issue when the extension want to build `bounty_tab.html`, it loads a svg file from huntr.dev (`https://huntr.dev/_nuxt/img/mouse-warrior.06d7a93.svg`), and this is prevented by the CSP rules of github.com

Hosting the SVG on github.com instead of huntr.dev will solve this.

> Thank you geeknik for the solution :)

You're welcome \m/

**Comment by JamieSlome** [comment]
@benharvie - can you confirm that this has now been fixed?

**Comment by benharvie** [comment]
This issue has now been fixed and released with the latest version which can be found here: https://addons.mozilla.org/en-US/firefox/addon/huntr/

Enjoy!

**Comment by geeknik** [comment]
@benharvie The extension quit working again.

**Comment by 0xcrypto** [comment]
How about making extension open source? Community will be able to contribute.
