### ISSUE TITLE
Suggestion: Notifications on the huntr.dev website itself

### ISSUE THREAD

**Issue by michaellrowley** [418sec/huntr#2089]
It'd be cool to see a 'notifications' area on the huntr.dev website so that I don't need to check my emails or manually go through reports to find out if a maintainer/admin has commented on a report.

**Comment by 0xcrypto** [comment]
This is already being tracked at https://github.com/418sec/huntr/issues/2035

**Comment by psmoros** [comment]
closing as duplicate of #2035 :)
