### ISSUE TITLE
Feature Request: Ability to filter submission by valid/invalid/pending

### ISSUE THREAD

**Issue by wr3nch0x1** [418sec/huntr#2091]
As a research, i would like to see how many reports are pending in my profile section for quickly follow ups and other calculations.
Thanks!

**Comment by JamieSlome** [comment]
@wr3nch0x1 - I am unclear on your request. We do currently display valid, invalid, and pending items on your user profile.

Let me know if I am misunderstanding! 🍰

**Comment by wr3nch0x1** [comment]
Ah, sorry, I overlooked pending tab. 
Apologies for inconvenience. Thanks!

**Comment by JamieSlome** [comment]
No worries, have a great day!
