### ISSUE TITLE
Researcher reputation score

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2094]
In line with:

https://discord.com/channels/672495759706554369/672516747202396209/871669175939104769

Thoughts from @0xcrypto:

>might only burden team with more work. I would say, bring back sheriffs. Maybe allow them to vote only instead of closing the report. And make their votes precious. Like for every positive vote that gets validated by maintainer, they receive more votes they can give to reports. For positive vote on invalid report, they dont receive their vote back.  Valid reports get more positive votes and bad reports will get negative votes. Even if the report has negative votes, maintainers will still have an option to consider the report. This way maintainers can save time.
Make all user a sheriff. Give each user 5 points to vote. If the user votes +1 on a valid report, he gets his vote back. If the user votes +1 on invalid report, he loses his vote. Just like bounty pool, refill the votes back to 5 every month.

**Comment by am0o0** [comment]
> Give each user 5 points to vote. If the user votes +1 on a valid report, he gets his vote back. If the user votes +1 on invalid report, he loses his vote. Just like bounty pool, refill the votes back to 5 every month.

i can make many account with some valid report on them and then can vote myself...i cant imagin how we can do it properly

**Comment by 0xcrypto** [comment]
> > Give each user 5 points to vote. If the user votes +1 on a valid report, he gets his vote back. If the user votes +1 on invalid report, he loses his vote. Just like bounty pool, refill the votes back to 5 every month.
> 
> i can make many account with some valid report on them and then can vote myself...i cant imagin how we can do it properly

Voting self should not be possible. Also, as @geeknik suggested, maybe reputated only accounts should be able to vote.

**Comment by am0o0** [comment]
no i mean i make some other accounts that already for mine and with them vote my main account
it is a serious problem that increase problems plus the main problem...

**Comment by am0o0** [comment]
As I talked with dear Jamie …
anyone can have any number of accounts
and then the rating can not be real
just it

**Comment by 0xcrypto** [comment]
> As I talked with dear Jamie …
> anyone can have any number of accounts
> and then the rating can not be real
> just it

I dont think people would take such a route just to get a few likes on their report. In the end it will be a decision of maintainer to accept or cancel the report. Also, it can be easily monitored. And if you read the concept again, it is similar to stackoverflow which works on the idea of reputation of a user. So higher the user is submitting correct reports or fixes, higher his reputation will be, then only he will be able to vote power.

**Comment by geeknik** [comment]
After thinking on this idea more, I'm no longer supportive of it, especially if the community needs access to our private bug reports in order to determine the validity. Not only does that undermine responsible disclosure, it also violates the principle of least privilege in my humble opinion. It's naive to think this won't be gamed or abused in some way.

**Comment by 0xcrypto** [comment]
> After thinking on this idea more, I'm no longer supportive of it, especially if the community needs access to our private bug reports in order to determine the validity. Not only does that undermine responsible disclosure, it also violates the principle of least privilege in my humble opinion. It's naive to think this won't be gamed or abused in some way.

agree the private bug reports should not be accessed by third party. But I dont think abusing it is possible.

**Comment by psmoros** [comment]
@0xcrypto @b1nslashsh @carakas do you guys still support this idea? 
Is it similar to #2024 or is it more rating researchers as the title says?

**Comment by b1nslashsh** [comment]
@psmoros 

No

**Comment by carakas** [comment]
I don't really see a big need for this

**Comment by psmoros** [comment]
Closing as no longer applicable :) feel free to reopen @0xcrypto if you still think it's relevant :)

**Comment by 0xcrypto** [comment]
> @0xcrypto @b1nslashsh @carakas do you guys still support this idea? Is it similar to #2024 or is it more rating researchers as the title says?

#2024 and #2156 would be more appropriate than this. Hackers would know whether the maintainer is non responsive while maintainers can know whether the hacker has a past of sending false reports.

**Comment by psmoros** [comment]
@0xcrypto great! Feel free to +1 the issues that you think are promising so that we follow through on them :)

**Comment by 0xcrypto** [comment]
done
