### ISSUE TITLE
Upload the Huntr browser extension's code to Github so the community can maintain it when it breaks

### ISSUE THREAD

**Issue by geeknik** [418sec/huntr#2095]
The Firefox extension is broken once again by platform backend changes, so could you please publish the code on GitHub so the community can maintain it?

**Comment by benharvie** [comment]
The huntr extension source code is now available here: https://github.com/418sec/huntr-extension

I willl enrich the repository further soon, looking forward to seeing your contributions ❤️ 

Cheers!
