### ISSUE TITLE
bug in new disclosure form 

### ISSUE THREAD

**Issue by am0o0** [418sec/huntr#2097]
![image](https://user-images.githubusercontent.com/77095239/128396988-a4874078-3bd2-413a-a608-c825a6a27316.png)
 as you can see in picture, the Location written twice and when I try to emit it I can't do that.

**Comment by am0o0** [comment]
here the link of example report, I figure out some of report have this problem....
https://huntr.dev/bounties/5b57f5f2-a055-4212-99c9-6ed1dea971f3/

**Comment by JamieSlome** [comment]
@psmoros - found another example:

https://huntr.dev/bounties/219ab652-1c4e-4b93-ab8a-3e3c5fc2152d/

Can we please investigate?

**Comment by am0o0** [comment]
> @psmoros - found another example:
> 
> https://huntr.dev/bounties/219ab652-1c4e-4b93-ab8a-3e3c5fc2152d/
> 
> Can we please investigate?

https://huntr.dev/bounties/ef691eeb-49ad-485f-ac40-73846ce40646/

**Comment by psmoros** [comment]
@amammad thanks for bringing this to our attention! I've diagnosed the issue and it will be fixed in the next release (in a week or two).
