### ISSUE TITLE
Display timestamp

### ISSUE THREAD

**Issue by dwisiswant0** [418sec/huntr#2099]
It will be helpful if the date of posting the disclosure or comment displays the exact time (timestamp).

![Screenshot_2021-08-06_04-07-19](https://user-images.githubusercontent.com/25837540/128421878-c9a4ec32-ec49-4bba-82f1-df2af6514646.png)
> (e.g. fill out `title` attribute value with `createdAt`)

Or maybe in the future, it should be considered again to be able to highlight comments by copying the permalink comment from the disclosure.

**Comment by JamieSlome** [comment]
Implemented and deploying 🎉 

You can now view the date and time of a comment or maintainer outreach notification by hovering over the dashed-underline time references.
