### ISSUE TITLE
Add cancel button for updating write-up

### ISSUE THREAD

**Issue by dwisiswant0** [418sec/huntr#2100]
Currently there is only a 'Save changes' button. This 'Cancel' button is very necessary since we can't exit the changes just by pressing `ESC` or some other shortcut, so we have to refresh the disclosure page.

**Comment by JamieSlome** [comment]
@psmoros - can we get your thoughts here from a UI/UX perspective?

Cheers! 🍰

**Comment by JamieSlome** [comment]
💡 Update

@dwisiswant0 - we are currently re-building our editing functionality for #2018.

**Comment by psmoros** [comment]
closing as sorted :) do you agree @dwisiswant0?

**Comment by dwisiswant0** [comment]
Sadly @JamieSlome & @psmoros, re-building the editing functionality that has been done is irrelevant to this.

I could just hit the Edit button **without making any changes** and hit Save, then record a new timeline showing up like this:
![Screenshot_2021-11-13_03-48-04](https://user-images.githubusercontent.com/25837540/141532680-9a3b19c1-4d5f-4d59-b69b-07523354ecd7.png)

Y'all should really consider this.
