### ISSUE TITLE
Able to mention users

### ISSUE THREAD

**Issue by dwisiswant0** [418sec/huntr#2101]
I'm not sure why using the `@admin` keyword in the comments can ping them. This _(username)_ mention should apply to all registered users on the platform, then of course the notification feature.

**Comment by JamieSlome** [comment]
@dwisiswant0 - certainly something we will look to implement!

I have added to our product backlog for the time being, and we will add updates when necessary.

Thanks for the suggestion! 🎉

**Comment by dwisiswant0** [comment]
I think it's a duplicate of #1989. Should we close this, @JamieSlome?

**Comment by JamieSlome** [comment]
@dwisiswant0 - yes, correct! ☑️ 

Closing...
