### ISSUE TITLE
Receive notifications from email

### ISSUE THREAD

**Issue by dwisiswant0** [418sec/huntr#2102]
Since #2101, this is necessary too. I thought if a comment came in from disclosure I would get a notification via email, but it didn't. I have to open my disclosure page!
Am I missing something about this important feature? Given the 'Settings' page is also not there.

**Comment by JamieSlome** [comment]
@dwisiswant0 - just to clarify, anytime someone comments on your disclosure, you will be notified that a comment has been added to that report.

Similarly, if you comment on another report, you will be notified of new comments on this report.

Are you receiving these e-mails?

**Comment by dwisiswant0** [comment]
No, I'm not, @JamieSlome.

I'm sign up to the platform using GitHub.

**Comment by JamieSlome** [comment]
@dwisiswant0 - the e-mail you will be receiving updates to will be the e-mail attributed to your GitHub profile.

**Comment by dwisiswant0** [comment]
> @dwisiswant0 - the e-mail you will be receiving updates to will be the e-mail attributed to your GitHub profile.

Exactly! But I do not receive notification updates in the email.

**Comment by JamieSlome** [comment]
@dwisiswant0 - please check your settings on your https://huntr.dev/users/dwisiswant0 profile, and you should see the e-mail that updates and notifications are being sent to.

**Comment by dwisiswant0** [comment]
> @dwisiswant0 - please check your settings on your https://huntr.dev/users/dwisiswant0 profile, and you should see the e-mail that updates and notifications are being sent to.

My email is correct anyway.

**Comment by dwisiswant0** [comment]
![IMG_20210807_011845.jpg](https://user-images.githubusercontent.com/25837540/128555015-80f0068b-92cb-4b45-bf8a-bc2d48cf8893.jpg)

Just received this when you commented with "👍".

Dunno why, I didn't make any changes btw.

**Comment by JamieSlome** [comment]
@zidingz - could be because of e-mail content improvements? See the above.

This might relate to #2002.

**Comment by zidingz** [comment]
@dwisiswant0 @JamieSlome 

Hey buddy,

Here are the logs for our email communications with you. We can see that you've opened one of the `New Comment` emails, while the other one remains delivered but unopened.

There is a chance that the email is hiding out in `Spam` or `Promotions` (if you're using Gmail). Could you kindly confirm what things look like on your side? Thanks!

<img width="1242" alt="Screenshot 2021-08-09 at 12 32 33" src="https://user-images.githubusercontent.com/28839565/128700062-d89a2fc3-61b3-45ae-a6df-b88b91ff0d25.png">

**Comment by dwisiswant0** [comment]
Ah, noted. After I looked it up in 'All inboxes', it looks like it's in the 'Promotions' category.

Last question: can I request to change my primary e-mail to receive those notifications?

**Comment by JamieSlome** [comment]
@adam-nygate - would this be covered by updating the primary e-mail address and then re-logging in, or would we need to manually updated for @dwisiswant0?

**Comment by adam-nygate** [comment]
> @adam-nygate - would this be covered by updating the primary e-mail address and then re-logging in, or would we need to manually updated for @dwisiswant0?

The email address we use is the one associated with their GitHub account. Currently, the only way this can be changed is by the user updating their email on GitHub - we can look to support a secondary email for users in the future though.

The reason why this cannot be addressed manually is that if we changed their email address on the backend, the next time the user logs in, it would re-sync with GitHub and be overridden by whatever information is present in GitHub at that time.

**Comment by dwisiswant0** [comment]
Noted. Got it then, addressed in new issue #2113.
