### ISSUE TITLE
After a session time-out, comments get lost

### ISSUE THREAD

**Issue by ehuelsmann** [418sec/huntr#2103]
Hi,

Last night, I was working on several reports on your site at the same time. I was logged in through the "magic URLs" provided in the notification mails for all of them. Due to the fact that I was working on several *and* discussing the reports with others in the project, it looks like the session opened by the magic URL timed out while I was compiling a comment: On clicking "Comment", there was a long waiting time and afterwards nothing changed (the comment wasn't added). Reloading the page didn't show the comment, although adding comments after the reload did work.

Could you have a look at providing the user with some feedback about session expiry and hopefully the original comment text (so it doesn't get lost)?

Thanks!

Regards,

Erik.

**Comment by JamieSlome** [comment]
@ehuelsmann - thanks for getting in touch and letting us know about this bug!

We are looking to identify the issue, and we will share updates once we have diagnosed and deployed a fix!

Thanks for your patience! 🎉

**Comment by JamieSlome** [comment]
@ehuelsmann - thanks for reporting.

After investigation, we boiled it down and have released a patch to prevent the timeout of comments. We have also added improved error tracking against this, to spot any issues quicker in the future.

**Comment by adam-nygate** [comment]
Will close this for now as we believe this to be resolved. We'll re-open if the issue occurs again.
