### ISSUE TITLE
URGENT: Need to document that CONFIRM FIX will GO PUBLIC

### ISSUE THREAD

**Issue by ehuelsmann** [418sec/huntr#2108]
Hi,

You urgently need to document that the effect of clicking "CONFIRM FIX" will publish the security "advisory" in the state it's currently in, with all the comments and all!

I was totally taken by surprise by that due to the lack of documentation of the process on your site.

THIS IS PART OF RESPONSIBLE DISCLOSURE TOO!!!

Regards,

Erik.

**Comment by ehuelsmann** [comment]
@adam-nygate can you please urgently assign me a CVE number for the vulnerability that's now published so I can properly inform my users?!

**Comment by adam-nygate** [comment]
Hey @ehuelsmann, will go ahead and close this ticket as we've solved the issue and are discussing long term fixes over live chat. Will create new tickets to track platform enhancements as necessary.
