### ISSUE TITLE
Researchers can permanently delete their account

### ISSUE THREAD

**Issue by geeknik** [418sec/huntr#2114]
I think researchers should have the ability to queue their accounts for deletion which would also then revert all pending disclosures from their username to `Anonymous Researcher`.

**Comment by adam-nygate** [comment]
Thanks for the suggestion! In the meantime, if anyone has the request, feel free to email me or any of the team to process this 😊

**Comment by psmoros** [comment]
@geeknik do you still support this initiative or can we close it?
