### ISSUE TITLE
Unable to fetch more disclosure data

### ISSUE THREAD

**Issue by dwisiswant0** [418sec/huntr#2123]
When I try to click "Show more" on https://huntr.dev/bounties/hacktivity/, it says `Uncaught (in promise) Error: GraphQL error: Invalid pagination token given.`

**Comment by JamieSlome** [comment]
@dwisiswant0 - thanks for the issue.

We will investigate ASAP.

**Comment by JamieSlome** [comment]
@dwisiswant0 - apologies for the delay of the update here!

We are no longer able to re-produce this issue. Can you confirm this is the case?

**Comment by psmoros** [comment]
@dwisiswant0 we'll consider this done. Feel free to reopen the issue if you're still experiencing this problem. Thanks!
