### ISSUE TITLE
Poor visibility (contrast) on desclosure form in Firefox

### ISSUE THREAD

**Issue by lkiesow** [418sec/huntr#2124]
The entries of the „Vulnerability Type“ drop-down are extremely hard to read due to their poor contrast.

- Firefox 91.0.2 on Linux
- Dark desktop theme (not sure if this is related)

![Screenshot from 2021-09-07 14-28-23](https://user-images.githubusercontent.com/1008395/132345862-897f3561-9feb-493f-9fd1-ccec4d6075cc.png)

**Comment by adam-nygate** [comment]
Was just about to fix this bug but looks like @JamieSlome beat me to it! Should be live now @lkiesow.

Feel free to re-open if the bug persists.

**Comment by adam-nygate** [comment]
Looks like the issue persists

**Comment by JamieSlome** [comment]
@adam-nygate - deployed and fixed now! 🎉
