### ISSUE TITLE
Reports fail to load when visiting transitively

### ISSUE THREAD

**Issue by jaapmarcus** [418sec/huntr#2128]
When I visit the "profile" or any other page and then "https://huntr.dev/users/jaapmarcus/reports" I see the following error in console.log

<img width="1433" alt="Screenshot 2021-09-10 at 13 31 26" src="https://user-images.githubusercontent.com/9754650/132847452-4a0204ca-7812-4d1e-9ccd-4365ff572b90.png">

See:

<img width="1764" alt="Screenshot 2021-09-10 at 13 35 38" src="https://user-images.githubusercontent.com/9754650/132847609-f2b404d7-27f5-4d9f-97f7-70560080c336.png">
 
 It seems to be an issue with websockets

**Comment by JamieSlome** [comment]
@adam-nygate - bump 👊

**Comment by jaapmarcus** [comment]
Please note if I visit straight to reports it works fine for first few seconds but after xx seconds the connection is lost again...

**Comment by adam-nygate** [comment]
> See:
> 
> <img alt="Screenshot 2021-09-10 at 13 35 38" width="1764" src="https://user-images.githubusercontent.com/9754650/132847609-f2b404d7-27f5-4d9f-97f7-70560080c336.png">
> 
> It seems to be an issue with websockets

It looks like our livechat provider is having websocket issues ("WebSocket connection to 'wss://app.chatwoot.com/cable' failed"). I'll drop them a message and ask them to investigate.

With regards to the network errors ("Error writing result to store for query"), I'm struggling to simulate them. I tried following your steps of navigating to the home page and then to the reports page, but don't get the error. Do you have any more details on how to cause that error?

**Comment by jaapmarcus** [comment]
Please DM me on Discord. I am in the the Huntr server with the same user name.  Then I am able to share a video how ever don't like the idea of sharing over Github as it contains some undisclosed vulnerabilities. 

But the basic: I go first to: "My Profile" and then "Avatar" => Reports => "Repository" the "Arrow down show fine but nu vulnerability are shown.

**Comment by adam-nygate** [comment]
> Please DM me on Discord. I am in the the Huntr server with the same user name. Then I am able to share a video how ever don't like the idea of sharing over Github as it contains some undisclosed vulnerabilities.

I can't seem to message/add you on Discord. Can you add me? Adzz# 0418

**Comment by adam-nygate** [comment]
Fixed.

**Comment by jaapmarcus** [comment]
👍🏼  Works fine
