### ISSUE TITLE
[Feature Request]: Make the validate button for maintainers more obvious.

### ISSUE THREAD

**Issue by Haxatron** [418sec/huntr#2130]

**Comment by JamieSlome** [comment]
@Haxatron - thanks for your suggestion and apologies for the delayed response! 😭 

Could you provide more detail into what is the issue that you are experiencing or what you are looking to achieve by making the validate button more obvious?

**Comment by Haxatron** [comment]
I think I made this post back when I was frustrated when maintainers issued a fix but forgot to validate my reports 😅. However, I do not have any issues with this anymore. My sincere apologies. You may close this issue.

**Comment by JamieSlome** [comment]
Closing! 🙏
