### ISSUE TITLE
Can we get the reports in a priority like the latest first?

### ISSUE THREAD

**Issue by ready-research** [418sec/huntr#2131]
Can we get the reports in a priority like the latest first? I am missing my track to check those. It is difficult for us to track our own reported issues.

**Comment by psmoros** [comment]
Working on it :)

**Comment by JamieSlome** [comment]
Update ⏰ 

We now order the reports on the reports page by newest first. Does this solve the problem that you were having @ready-research?

**Comment by geeknik** [comment]
Hi @JamieSlome, I can see the latest report first, but all of the rest are still out of order even after refreshing. 

![image](https://user-images.githubusercontent.com/466878/140777563-da01ccd6-434c-4e84-a14a-591deb07262d.png)

**Comment by JamieSlome** [comment]
@geeknik - we do not have the order by date on the repositories, but in each repository row, the reports will be ordered by date. How would you want the ordering per repository to work?

**Comment by geeknik** [comment]
Oh, I misunderstood, I thought all of the reports on https://huntr.dev/users/geeknik/reports/ would be ordered by last report first, irregardless of which repository they were part of.

**Comment by psmoros** [comment]
tracked in #2163 :)
