### ISSUE TITLE
[Bug] GitHub url casesensitive

### ISSUE THREAD

**Issue by jaapmarcus** [418sec/huntr#2133]
See screenshots below

<img width="1275" alt="Screenshot 2021-09-15 at 16 08 45" src="https://user-images.githubusercontent.com/9754650/133777672-17274a1b-7d65-4fdd-a546-467405c0deb7.png">

<img width="1262" alt="Screenshot 2021-09-15 at 16 07 35" src="https://user-images.githubusercontent.com/9754650/133777719-0430161a-6490-4a99-b6fe-6bad5c573fe8.png">

**Comment by adam-nygate** [comment]
This has now been fixed :)
