### ISSUE TITLE
As a user, I want reports to be compensated more fairly.

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2136]
# Stories

- [x] As a maintainer, I want to define the reward for a disclosure (https://github.com/418sec/huntr-platform/issues/1656)

# Requirements

- [x] Update target finder to reflect a range of rewards from $0 to...
- [x] On the report page, reflect a range of rewards from $0 to...
- [x] The upper limit of rewards is defined by the default popularity score
- [x] The lower limit of all reports is $0
- [x] Recalculate permalink bounties, disclosure bounty, and fix bounty using maintainer elected report bounty
- [x] Store both the original and base price of disclosure in database.

**Comment by JamieSlome** [comment]
Delivery deadline:

Wednesday - 29th September

**Comment by JamieSlome** [comment]
Just as a status update, so far we have:

- Implemented our business logic on our backend to ensure maintainer selections are supported
- Implemented the front-end views to support the business logic

Tomorrow:

🪝 Hooking up GraphQL to our front-end requirements...

**Comment by JamieSlome** [comment]
Status of this ticket @adam-nygate? ❤️

**Comment by adam-nygate** [comment]
> Status of this ticket @adam-nygate? ❤️

Is 418sec/huntr-platform#1807 live?

**Comment by JamieSlome** [comment]
Live and kickin' 🙏
