### ISSUE TITLE
As a maintainer, I want to receive fewer notifications of inconsiquential reports.

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2137]
- [x] As a maintainer, I want to receive fewer notifications of inconsequential reports. (https://github.com/418sec/huntr-platform/issues/1651)

**Comment by JamieSlome** [comment]
Implemented and deployed 🎉 🚀 

Close when ready.

**Comment by JamieSlome** [comment]
Closing! I have received confirmation from @adam-nygate... 🎉
