### ISSUE TITLE
As a security researcher, I want to be proud when I share huntr pages.

### ISSUE THREAD

**Issue by adam-nygate** [418sec/huntr#2138]
- [ ] Profile meta card
- [x] Report meta card
- [x] Privatise money

**Comment by TheCrott** [comment]
> * [ ]  Referral cards
> * [ ]  Privatise money

What is referral cards and privatise money?

**Comment by adam-nygate** [comment]
The card (WIP) preview:
![image](https://user-images.githubusercontent.com/4394852/135308162-497b3e88-6d83-4e9e-b6c9-2a705521e2e0.png)

Privatise money is to make money confidential and so can only be seen by the respective researcher/maintainer (we shipped this today :D)

**Comment by JamieSlome** [comment]
As part of this scope, should we consider overhaul/changes on existing `head` tags like `description` etc. for when links are shared?
