### ISSUE TITLE
As a maintainer, I want to see more details in the Reports list

### ISSUE THREAD

**Issue by mvz** [418sec/huntr#2147]
I'd like to see more details in the Reports list so I know what I still need to do without having to open each report. In particular, I'd like to see the statuses 'patch received' and 'fixed'.

**Comment by JamieSlome** [comment]
@mvz - we are going to be addressing this shortly - apologies for the delay in response.

@psmoros - just to confirm, on the maintainer delighters mentioned, will this be in scope?

**Comment by psmoros** [comment]
yeah absolutely! We aim to open a ticket on the roadmap this week with a deadline so that you can keep track of this request @mvz :)

**Comment by psmoros** [comment]
tracked in #2163 :)
