### ISSUE TITLE
Add more CWE

### ISSUE THREAD

**Issue by am0o0** [418sec/huntr#2149]
hey guys 

Can I ask you to add these CWEs that related to bypass the rate limits
770 
799
307
400

**Comment by JamieSlome** [comment]
@adam-nygate ?

**Comment by adam-nygate** [comment]
770 already exists, but we can add the rest.

@JamieSlome can you add these and use 770 as the template? I.e `0` pricing multiplier and `false` cve flag

**Comment by JamieSlome** [comment]
@adam-nygate - all added! 🎉 

400 and 307 already existed in the database as well!
