### ISSUE TITLE
Join the fight leads to 404

### ISSUE THREAD

**Issue by jaapmarcus** [418sec/huntr#2150]
<img width="426" alt="Screenshot 2021-10-23 at 18 25 48" src="https://user-images.githubusercontent.com/9754650/138564175-ed7412c9-ae1a-4ce8-9b0e-2a550cbd57e6.png">

**Comment by JamieSlome** [comment]
@jaapmarcus - deploying a fix now! ❤️ 

Thank you for reporting.

**Comment by JamieSlome** [comment]
Fixed! 🎉
