### ISSUE TITLE
Users can track the status of their reports

### ISSUE THREAD

**Issue by psmoros** [418sec/huntr#2163]
Both researchers and maintainers are having trouble using the reports page #2127 #2131 #2147 
It has to be overhauled so as to allow users to stay on top of their submissions and maintainers on top of their reports.

> Need a search and sort option on the reports page @b1nslashsh 

> Can we get the reports in a priority like the latest first? I am missing my track to check those. It is difficult for us to track our own reported issues. @ready-research 

> I'd like to see more details in the Reports list so I know what I still need to do without having to open each report. In particular, I'd like to see the statuses 'patch received' and 'fixed'. @mvz

**Comment by psmoros** [comment]
migrated the +1 reactions from #2131 and #2147

**Comment by psmoros** [comment]
maybe #2122 can also be addressed with this work

**Comment by psmoros** [comment]
finished 13 days ago :)

**Comment by psmoros** [comment]
@b1nslashsh @ready-research as researchers, let me know if the new 'submissions' tab satisfies this request; and @mvz please lmk as a maintainer if the new 'repositories' tab addresses your needs :))

Thanks for improving huntr for everyone else!

**Comment by mvz** [comment]
@psmoros it looks like the repositories tab gives a nice at-a-glance overview, thanks!
