### ISSUE TITLE
See public reports tied to a repository

### ISSUE THREAD

**Issue by psmoros** [418sec/huntr#2165]
> It would actually be awesome, because as a beginner, there are so many types of applications I haven't tested yet, and I could learn new concepts from other people submissions. For example, Axios is a lib that I use a lot when developing applications, but I  have no clue of what things could go wrong with it.

from @therealbrenu on discord

+1 from IndecisiveSpaz , @HDVinnie, Aldo on discord :)

**Comment by psmoros** [comment]
@HDVinnie @jaapmarcus @ritiksahni @brenu @khanhchauminh @TheCrott have a play with [hacktivity](https://huntr.dev/bounties/hacktivity) and let me know if you're satisfied with how this ticket has been delivered :))

**Comment by brenu** [comment]
Yeah! It's perfect! 🤗

**Comment by HDVinnie** [comment]
LGTM ❤️

**Comment by ritiksahni** [comment]
Very useful - thank you!

**Comment by khanhchauminh** [comment]
Great feature! It's very useful! 🤗
