### ISSUE TITLE
Sort repos by programming languages

### ISSUE THREAD

**Issue by Scara31** [418sec/huntr#2172]
Feature proposal:
Add a list with all repos which you can sort by programming languages (sort by technologies, e.g. React, GraphQL, etc would be nice too, but it should be a bit harder to implement - the first feature simply needs to collect the info from repos' GitHub page)

**Comment by psmoros** [comment]
hey @jaapmarcus @khanhchauminh @HDVinnie and @tomaarsen sorry for spamming you on previous tickets today. It's that this delivery addressed many tickets but for whoever wasn't tagged in the previous ones, do you mind having a play with the new search bar on the [hacktivity](https://huntr.dev/bounties/hacktivity) page and letting me know if this ticket has been met to your satisfaction? Thanks a lot!
