### ISSUE TITLE
Remind maintainers of outstanding reports without patches

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2177]
<img width="782" alt="Screenshot 2021-12-09 at 14 10 12" src="https://user-images.githubusercontent.com/55323451/145411702-6e2ad5c4-4957-4fe2-9270-ab21e1e211f0.png">

**Comment by jaapmarcus** [comment]
Maybe 1 week after validation and then every month after that...

**Comment by psmoros** [comment]
Done :)
