### ISSUE TITLE
Confusion around how prize pot freezing works

### ISSUE THREAD

**Issue by JamieSlome** [418sec/huntr#2199]
Reference: https://www.huntr.dev/bounties/ea82cfc9-b55c-41fe-ae58-0d0e0bd7ab62

<img width="773" alt="Screenshot 2022-03-07 at 09 53 33" src="https://user-images.githubusercontent.com/55323451/157008355-746c425c-eee5-4302-88f4-e7b310756e8e.png">

**Comment by ysf** [comment]
The main problem I see here is that researchers will benefit from holding back an issue until the prize pot has been filled again. This can result in an cascade over and over again. With lot of submissions when the prize is available and more people holding back for the next round.

I don't have a solution for this, I just can just deconstruct it. And of course would've liked to get a bounty for a critical issue in a big project.

**Comment by psmoros** [comment]
Underlying issue persists but freezing has been deprecated

**Comment by ysf** [comment]
Can you elaborate more? I'm still missing answers to the questions raised.
