### ISSUE TITLE
[ Bug ] UI Edit button and "Not verified" overlap

### ISSUE THREAD

**Issue by jaapmarcus** [418sec/huntr#2215]
<img width="788" alt="Screenshot 2022-04-24 at 13 28 21" src="https://user-images.githubusercontent.com/9754650/164974290-dbd84f22-a4fb-47ad-8704-28dfd2a25c63.png">

Buttons works as expected.

Safari 15.4 OSX Last release

**Comment by psmoros** [comment]
Fixed :)

**Comment by jaapmarcus** [comment]
👍🏼
