### ISSUE TITLE
Feature Request for private visibility

### ISSUE THREAD

**Issue by Gaurav-G2** [418sec/huntr#2221]
Hi admin 
Im using your service as bug hunter i want to know if you can add a feature where researcher and maintainer can decide whether they want to make the report public or private visible after resolving the report

**Comment by jaapmarcus** [comment]
Reports should always be public mainly if the bounties are paid by a 3rd company it can be used for learning and so on.  For open source at least it doesn't make sense as any changes 

If you don't want your reports to be public disclose them via email directly to the maintainer.

Only exceptions are and allow a delay for x days to make sure users are able to update before releasing of the report.
https://github.com/418sec/huntr/issues/2143
