### ISSUE TITLE
Duplicates should not result in a loss of accuracy

### ISSUE THREAD

**Issue by 7085** [418sec/huntr#2223]
Currently when a report is marked as a duplicate, the accuracy goes down.
I think this should not happen, as long as the first report is not public and is valid.
Since there is no way to know this in advance, there should not be any negative consequences.
This should only happen when a public report (or information about the exact same vulnerability) already exists.

**Comment by psmoros** [comment]
This has been addressed :) Thank you all for your contribution @7085 @galapag0s @greatergoodest
