### ISSUE TITLE
[Bug] Entering "/" in text field will change focus to new "short" menu in top browser

### ISSUE THREAD

**Issue by jaapmarcus** [418sec/huntr#2270]
We writing up a report or editing security policy and entering an / the focus of the window will change to the new search bar...

https://user-images.githubusercontent.com/9754650/174607021-6ca4c931-c9d9-4741-a4d4-a4b0eff4be3b.mov

When the browser has been focused on a input / text area it should not go to the "new" search bar when you press /. 

Input field works as expected

**Comment by JamieSlome** [comment]
@jaapmarcus - fixing now 👍

**Comment by JamieSlome** [comment]
Fixed 🚀
