### ISSUE TITLE
As a huntr, I would like to know (without going to GitHub) if somebody has already got a PR in.

### ISSUE THREAD

**Issue by stemount** [418sec/huntr#273]
Of course, not all PRs entered are actually bugfixes, maybe a misunderstanding or maybe something that causes breaking changes.

For myself, I find it slow to navigate for issues that do not have a pull request for the issue and if it does, I have to go to the original issue in GitHub, it would be good to have:

1. A count of PRs open against an issue
2. Maybe some way of tracking the "amount of time it takes" to get a PR request reviewed (or declined).
2a. this would really help provide a feedback loop to all that there was not an "accepted fix" because of side effects, breaking changes, not actually resolving the issue etc...

**Comment by JamieSlome** [comment]
@stemount - thanks for the suggestion. We have added this to our backlog and will keep the issue updated with any changes on this!

Cheers! 🍰

**Comment by JamieSlome** [comment]
@stemount - (1) has now been implemented and is live on the platform. Feel free to take a look at any bounty page to see the open PRs against a bounty.

Regarding (2), we will track this as a separate issue request...

Cheers! 🍰
