### ISSUE TITLE
Why expose vulnerabilities publicly before fixing them? 🤔

### ISSUE THREAD

**Issue by karuppiah7890** [418sec/huntr#786]
For reference: https://github.com/karuppiah7890/easy-pdf-merge/pull/28#issuecomment-709435039

**Comment by JamieSlome** [comment]
@karuppiah7890 - thanks for creating the issue and for getting in touch!

We want to encourage public discussion around security vulnerabilities as opposed to following a model of security through obscurity. Furthermore, we believe that it can be practical to approach maintainers with a concrete fix in place without the maintainer or its community having to worry about how to address this.

That said, we are looking to address public vs. private disclosure in the near future, allowing maintainers to have this opportunity to choose whether they are comfortable with these code-level vulnerabilities being addressed in the open.

Let me know if you have any more questions, or want to talk further together about this.

Cheers! 🍰

**Comment by karuppiah7890** [comment]
I think that answers it 👍
